services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miet-schedule-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro 
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: miet-schedule-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www:ro 
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge